---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-8.4.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-8.4.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-8.4.0-amd64
    box_check_update: true

- name: ubuntu-14.04.4-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ubuntu-14.04.4-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.4-server-amd64
    box_check_update: true

suites:
- name: default
  run_list:
    - recipe[papertrail::default]
  attributes: {}